version: '2'
services:

  redis:
    image: redis:latest
    command: ["redis-server", "--requirepass", "apilayer"]
        
  kong-database:
    image: postgres:9.5
    container_name: kong-database
    volumes: 
        - ./storage/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: your_pwd

  kong:
    image: kong:latest
    restart: always
    links:
      - kong-database:kong-database
    volumes:
       - ./src:/usr/local/openresty/site/lualib/kong/plugins/response-cache
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 7946:7946
      - 7946:7946/udp
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=your_pwd
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PLUGINS=bundled,response-cache
      - KONG_LOG_LEVEL=debug
    entrypoint: ["tail", "-f", "/dev/null"]
    # command: ["kong", "start", "--run-migrations", "-vvv"]
    # command: ["kong", "start", "-vv"]
